### ISSUE TITLE
Polygon Union returning 2 different result with a small change in location of an independent point

### ISSUE THREAD

**Issue by vidit1** [voidqk/polybooljs#12]
Hi,
Have a look at the red polygon's bottom rightmost point. By changing the location its position by few pixels the result is changed. Adding the images showing this case.
1st image - result is a single polygon which is union of both the polygon.
2nd image - returning the 2 polygons as is.
 
<img width="1280" alt="screen shot 2018-04-24 at 8 58 52 pm" src="https://user-images.githubusercontent.com/8842788/39197896-521c03d6-4803-11e8-9803-a3dc4947fda9.png">
<img width="1280" alt="screen shot 2018-04-24 at 9 06 27 pm" src="https://user-images.githubusercontent.com/8842788/39197980-8465c5f2-4803-11e8-9b6f-a7602474cdd4.png">

**Comment by voidqk** [comment]
The result is still correct though, right?

Why do you think this behavior is a bug?

The first result is a big region, that hits `[25,15]` twice... the second result is two regions, both of which contain `[25,15]`.  Either representation is valid, unless I'm missing something.

**Comment by vidit1** [comment]
The data is inconsistent.
I have to check if union of 2 or more polygon results in a single polygon, In first case that is true but in second case it is false. There is no single source of truth.

**Comment by voidqk** [comment]
A union can always return multiple regions.  That's the nature of union.  Here's a trivial example:

![](http://sean.cm/i/polygon-clipping-pt2/union-ex.png)

It might help you to read through how the algorithm works -- I have a tutorial [here](http://sean.cm/a/polygon-clipping-pt2).

This library makes no promise about the number of regions returned, and has no preference for smaller lists of regions.

The data is consistent in the sense that the same input will always return the same output.  But different input results in different output.  You changed the data, so the algorithm pieces together the result in a different way, with no preference for region count, and produces two regions instead of one.  This is normal behavior.

**Comment by vidit1** [comment]
You are correct union can return multiple polygon. 
That is what i am looking for, i want to check that when i perform a union operation on 2 or more polygons the result is a single polygon or not.
In the library when 2 polygons are linked through a single point, union operation returns sometimes single polygon and sometimes multiple polygon.
I just want to know why this is happening.

**Comment by voidqk** [comment]
It has to deal with the segment chaining algorithm.

If you use the animation on the demo page, and hit Left/Right, you can see the segment chaining process.

The order that the segments are added determines whether there are one or two regions.  This order is dependent on the vertical alignment.

In the below pic, point B is to the right of point A -- this means that when the chaining is happening (below), it will add the segment C->A before the segment C->B.  The highlighted segment then doesn't complete a loop, so the result will be a single region.

If instead point B is to the left of point A, then C->B will be added first, closing the region.  Then when C->A is added, it creates a new chain, that eventually turns into the second region.

<img width="532" alt="screen shot 2018-04-26 at 8 28 40 am" src="https://user-images.githubusercontent.com/8442338/39305881-9e694abc-492c-11e8-8eb0-745b33e1a6dd.png">
